# Generated by Django 3.2.8 on 2021-11-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(default=10.0)),
                ('uploaded_price', models.FloatField(default=10.0)),
                ('msawm_team_price', models.FloatField(default=10.0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50)),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_subcategories', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
    ]
